# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :


# Base box
VAGRANT_BOX = 'generic/ubuntu2010'

# VM Name
VM_NAME = 'ubuntu20'

# VM User — 'vagrant' by default
VM_USER = 'vagrant'

# Host folder to sync
HOST_PATH = '/home/sean/Desktop/prod-dev-src'

# Where to sync to on Guest
GUEST_PATH = '/home/' + VM_USER + '/dev'

# VM Port — uncomment this to use NAT instead of DHCP
# VM_PORT = 8080


Vagrant.configure(2) do |config|  
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VM_NAME
  config.vm.define VM_NAME
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 4096
    v.cpus = 4
  end  
  #DHCP — comment this out if planning on using NAT instead
  config.vm.network "private_network", type: "dhcp"
  # Port forwarding — uncomment this to use NAT instead of DHCP
  # config.vm.network "forwarded_port", guest: 80, host: VM_PORT 
  # Sync folder
  config.vm.synced_folder HOST_PATH, GUEST_PATH  
  # Disable default Vagrant folder, use a unique path per project
  config.vm.synced_folder '.', '/home/'+VM_USER+'', disabled: true
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git make vim gcc gdb docker docker-compose curl net-tools wget nodejs build-essential npm golang-go
    apt-get update
    apt-get upgrade -y
    apt-get autoremove -y
  SHELL
end
